# Permalinks
permalink:        pretty

# Setup
title:            Statistiline andmeteadus ja visualiseerimine
tagline:          MTMS.01.100
url:              http://andmeteadus.github.io/
paginate:         1
baseurl:          /2021
author:
  name:           Kaur Lumiste, Tanel Pärnamaa, Kaspar Märtens, Taavi Unt
  url:            
  email:          kaur.lumiste@ut.ee

# Custom vars
version:          1.0.0
github:
  repo:           http://andmeteadus.github.io/2020

pages_list:       
  Praktikumid: '/praktikumid'
  Projektid: '/projektid'
  Huvitavat materjali: '/materjalid'
